version: '3.7'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    volumes:
      - ./tests:/scripts
    command: run --out influxdb=http://influxdb:8086/k6 /scripts/load_test.js

volumes:
  influxdb-data:
  grafana-data:
